### ISSUE TITLE
Stomping on local state

### ISSUE THREAD

**Issue by delaneyj** [bfitch/cerebral-falcor-module#3]
[Made a new boilerplate for testing this module](https://github.com/delaneyj/cerebral-snabbdom-falcor-boilerplate).

The initial commit shows the stomping of the 'page' in baobab when getting the title from falcor.

**Comment by bfitch** [comment]
Thanks for reporting this @delaneyj and reproducing the issue in that boilerplate...super helpful! So what's happening is that the `falcor` cache syncs its changes to `baobab`. In this case, falcor knows nothing about `{page: 'about'}`: that state only lives in `baobab`. When falcor `get()` is executed to grab the `{title: ''}`, falcor's cache is updated, then diffed with baobab. So they look like this during the diff:

``` js
const baobab = {
  title: 'Loading...',
  page: 'about'
}

const falcorCache = {
  title: 'A title from falcor'
}
```

The diff calculates that the `page` key has been removed (since falcor knows nothing about it) and once the diff is applied to `baobab` it looks like this:

``` js
const baobab = {
  title: 'A title from falcor',
  page: undefined
}
```

which causes the "trampling" of state you reported.

#### What to do about it?
1. Namespace all falcor data under a `{falcor: {}}` key in baobab and then only compare that namespaced data during the diff, so all non-falcor values won't be touched.
   
   I tried this out really quick, but it fell apart when trying to fetch data from the falcor router. The falcor router needs to know the paths of data requested and when I tried to `get(['falcor', 'title'])` and return namespaced paths the falcor router and/or cache did not set the `title` path correctly on the client. Perhaps there's a way to get think working, just need to dig into the router a little more or bug falcor devs about it :stuck_out_tongue: .
2. Make `falcor-baobab` sync bi-directional. So every change to baobab is pushed to falcor's cache and every change to falcor is pushed to baobab, keeping them perfectly in sync.
   
   I think number 2 is the way to do. But, I need to do a little work and add some tests as it's a bit more complicated to implement. Also need to be careful with race conditions when responding to model and falcor change events.

Anyway, thank you for reporting this bug. I'm going to work to resolve it and will update you on my progress. Thanks!

**Comment by bfitch** [comment]
Discussed with @delaneyj on gitter: 

> might be as simple as mapping `falcor['title']` to `baobab['falcor', 'title']`, then calling `falcor.get(['title'])` like normal, and just diffing `falcorCache.get()` with `baobab.get(['falcor'])`

**Comment by bfitch** [comment]
Fixed: https://github.com/bfitch/cerebral-falcor-module/releases/tag/v0.2.0 

`npm install cererbral-falcor-module@0.2.1 --save`
